from e2b_code_interpreter import Sandbox
import os

def execute_gee_code(generated_code):
    """
    Execute the generated GEE Python code in a sandbox environment.
    
    Args:
        generated_code (str): Python code generated by code_generator.py
        
    Returns:
        str: Output from the executed code
    """
    # Create sandbox instance (by default, sandbox instances stay alive for 5 mins)
    sbx = Sandbox("e38dmuuvhb0pkkfztlt5")
    
    # Clean the code if it contains markdown formatting
    if "```python" in generated_code:
        code = generated_code.split("```python")[1].split("```")[0]
    else:
        code = generated_code
    
    print("\nExecuting code in sandbox...")
    execution = sbx.run_code(code)
    
    # Extract the output
    stdout = execution.logs.stdout[0] if execution.logs.stdout else ""
    
    return stdout 